version: "3"

volumes:
    db:

services:
  worker: &worker
    build:
      context: .
      dockerfile: ./dockerfiles/local/Dockerfile
    env_file:
      - .env/.local/django
    depends_on:
      - db
      - redis
    command: celery -A timetracker worker -B -l debug
    networks:
      - default

  web:
    <<: *worker
    volumes:
      - ./media:/media
      - ./timetracker:/app/timetracker
#      - ./pyproject.toml:/app/pyproject.toml
      - ./pytest.ini:/app/pytest.ini
#      - ./.flake8:/app/.flake8
    command: >
      sh -c "urlwait &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8100:8000"
      - "587:587"
    networks:
      default:

  db:
    image: postgres:12
    env_file:
      - .env/.local/postgres
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:latest
